import java.util.List;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs){
        //TODO: write code here
        int num = inputs.size();
        String[] item = new String[num];
        String[] itemId = new String[num];
        int count = 0;

        List<String> id = itemRepository.findAll().stream().map(Item::getId).collect(Collectors.toList());
        List<String> name = itemRepository.findAll().stream().map(Item::getName).collect(Collectors.toList());
        List<Double> price = itemRepository.findAll().stream().map(Item::getPrice).collect(Collectors.toList());

        List<String> promotion = salesPromotionRepository.findAll().stream().map(SalesPromotion::getDisplayName).collect(Collectors.toList());
//      List<String> pro_item = salesPromotionRepository.findAll().stream().map(SalesPromotion::getRelatedItems).collect(Collectors.toList());

        int total = 0,discount1=0,discount2=0;
        String item_name = "";
        String item_res = "";
        String pro_item = "";
        boolean flag = false;
        int item_price = 0;
        int total_yuan = 0;
        int saving = 0;
        String pro_display = "";
        String res = "";

        for (int i=0; i<num; i++){
            item[i] = inputs.get(i); //输入的每个item信息
            count = item[i].charAt(item[i].length()-1) - '0'; //每个item分割后的数量
            itemId[i] = item[i].substring(0, item[i].indexOf(" ")); //每个item分割后的id

            int index = id.indexOf(itemId[i]);
            item_name = name.get(index);
            item_price = price.get(index).intValue();
            total += item_price * count;
            if(itemId[i].equals("ITEM0001") || itemId[i].equals("ITEM0022")){
                discount2 += item_price / 2 * count;
                pro_item += item_name + "，";
                flag = true;
            }
            else{
                discount2 += item_price * count;
            }
            item_res += item_name + " x " + count + " = " + item_price * count + " yuan\n";
        }

        if(total > 30){
            discount1 = total - 6;
            flag = true;
        }
        if(flag){
            if(discount1 > discount2){
                total_yuan = discount2;
                saving = total - total_yuan;
                pro_display += promotion.get(1) + " (" + pro_item.substring(0,pro_item.length()-1) + ")";
            }else{
                total_yuan = discount1;
                saving = total - total_yuan;
                pro_display += "满30减6 yuan";
            }
        }
        if(flag) {
            res = "============= Order details =============\n" +
                    item_res +
                    "-----------------------------------\n" +
                    "Promotion used:\n" +
                    pro_display + "，saving " + saving + " yuan\n" +
                    "-----------------------------------\n" +
                    "Total：" + total_yuan + " yuan\n" +
                    "===================================";
        }
        else {
            res = "============= Order details =============\n" +
                    item_res +
                    "-----------------------------------\n" +
                    "Total：" + total + " yuan\n" +
                    "===================================";
        }
        return res;
    }
}
